### ISSUE TITLE
Better grouping for identical value pseudo rules

### ISSUE THREAD

**Issue by Zn4rK** [eagerpatch/navita#20]
```typescript
const x = style({
  '&:hover': {
    background: 'red',
  }
});

const x2 = style({
  '&:active': {
    background: 'red',
  }
});
```

Will produce the following css:

```css
.a1:hover {
  background: red;
}

.b1:active {
  background: red;
}
```

But it could produce the following CSS to save a few bytes:

```css
.a1:hover, .b1:active {
   background: red;
}
```
