### ISSUE TITLE
Make sure `normalizeCSSVarsValue` runs for more cases

### ISSUE THREAD

**Issue by Zn4rK** [eagerpatch/navita#21]
```typescript
const color = createVar('color');

const x = style({
   background: `rgba(${color}, 0.15)`,
});
```

Will produce this css:
```css
.a1 {
   background: rgba(--color, 0.15);
}
```

Instead of this:
```css
.a1 {
   background: rgba(var(--color), 0.15);
}
```

Source:
https://github.com/eagerpatch/navita/blob/main/packages/engine/src/helpers/normalizeCSSVarsValue.ts#L3

At first glance, it looks like the regex is still valid, but we need to expand the test cases, and modify or remove the if-statement that decides if we should normalize CSS var values.
